{
 "title": "XCM Monitoring Server",
 "tags": [ "xcm" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Websocket Listeners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (xcmon_socket_listener_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xcmon_active_subscriptions_count",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (__name__) (xcmon_subscription_errors_count)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xcmon_root_db_disk_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Notification Errors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (origin, destination) (sum_over_time(xcmon_notifier_notification_error_total[$__interval]))",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (origin, destination) (sum_over_time(xcmon_notifier_notification_total[$__interval]))",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xcmon_catcher_block_height", "legendFormat": "{{origin}}" }
   ]
  },
  {
   "title": "Finality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(xcmon_catcher_block_finalized_seconds_sum[$__rate_interval])\n/ rate(xcmon_catcher_block_finalized_seconds_count[$__rate_interval])",
     "legendFormat": "{{origin}}"
    }
   ]
  }
 ]
}