[[substrate.networks]]
id = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc.ibp.network/polkadot",
    "wss://rpc.dotters.network/polkadot",
    "wss://polkadot-rpc.dwellir.com",
    "wss://polkadot-rpc.publicnode.com"
  ]
[[substrate.networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"
   [substrate.networks.provider]
   type = "rpc"
   url = [
    "wss://sys.ibp.network/asset-hub-polkadot",
    "wss://asset-hub-polkadot.dotters.network",
    "wss://polkadot-asset-hub-rpc.polkadot.io",
    "wss://asset-hub-polkadot-rpc.dwellir.com"
   ]
[[substrate.networks]]
id = "urn:ocn:polkadot:1002"
relay = "urn:ocn:polkadot:0"
   [substrate.networks.provider]
   type = "rpc"
   url = [
    "wss://sys.ibp.network/bridgehub-polkadot",
    "wss://bridge-hub-polkadot.dotters.network",
    "wss://bridge-hub-polkadot-rpc.dwellir.com",
    "wss://polkadot-bridge-hub-rpc.polkadot.io"
   ]

## Kusama

[[substrate.networks]]
id = "urn:ocn:kusama:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc.ibp.network/kusama",
    "wss://rpc.dotters.network/kusama",
    "wss://kusama.api.onfinality.io/public-ws"
  ]
[[substrate.networks]]
id = "urn:ocn:kusama:1000"
relay = "urn:ocn:kusama:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://sys.ibp.network/statemine",
    "wss://asset-hub-kusama.dotters.network",
    "wss://rpc-asset-hub-kusama.luckyfriday.io",
    "wss://kusama-asset-hub-rpc.polkadot.io",
    "wss://asset-hub-kusama-rpc.dwellir.com"
  ]
[[substrate.networks]]
id = "urn:ocn:kusama:1002"
relay = "urn:ocn:kusama:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://sys.ibp.network/bridgehub-kusama",
    "wss://bridge-hub-kusama.dotters.network",
    "wss://kusama-bridge-hub-rpc.polkadot.io"
  ]