[[substrate.networks]]
id = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://polkadot-rpc.n.dwellir.com",
    "wss://polkadot-rpc-tn.dwellir.com",
    "wss://rpc-polkadot.luckyfriday.io",
    "wss://rpc-polkadot.stakeworld.io",
    "wss://rpc-polkadot.helixstreet.io"
  ]
[[substrate.networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"
    [substrate.networks.provider]
    type = "rpc"
    url = [
      "wss://polkadot-asset-hub-rpc.polkadot.io",
      "wss://dot-rpc.stakeworld.io/assethub",
      "wss://rpc-asset-hub-polkadot.luckyfriday.io",
      "wss://statemint.public.curie.radiumblock.co/ws",
      "wss://asset-hub-polkadot-rpc.n.dwellir.com",
      "wss://statemint-rpc-tn.dwellir.com"
    ]

 [[substrate.networks]]
 id = "urn:ocn:polkadot:2034"
 relay = "urn:ocn:polkadot:0"
      [substrate.networks.provider]
      type = "rpc"
      url = [
        "wss://hydration-rpc.n.dwellir.com",
        "wss://rpc.hydradx.cloud"
      ]

# [[substrate.networks]]
# id = "urn:ocn:polkadot:2000"
# relay = "urn:ocn:polkadot:0"
#     [substrate.networks.provider]
#     type = "rpc"
#     url = [
#     # "wss://acala-rpc-0.aca-api.network",
#     # "wss://acala-rpc-1.aca-api.network",
#     # "wss://acala-rpc-3.aca-api.network/ws",
#     "wss://rpc-acala.luckyfriday.io",
#     "wss://acala-rpc.n.dwellir.com"
#     ]

# [[substrate.networks]]
# id = "urn:ocn:polkadot:2004"
# relay = "urn:ocn:polkadot:0"
#   [substrate.networks.provider]
#   type = "rpc"
#   url = [
#     # "wss://moonbeam.ibp.network",
#     "wss://wss.api.moonbeam.network",
#     "wss://moonbeam-rpc.dwellir.com"
#   ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2034"
relay = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://hydration-rpc.n.dwellir.com",
    "wss://rpc.hydradx.cloud",
    "wss://hydration.rotko.net"
  ]

# ==========================================
# EVM networks
# ==========================================

[[evm.networks]]
id = "urn:ocn:ethereum:222222"
maxBlockDist = 150
    [evm.networks.provider]
    type = "rpc"
    url = [
      "https://hydration-rpc.n.dwellir.com",
      "https://rpc.hydradx.cloud"
    ]

[[evm.networks]]
id = "urn:ocn:ethereum:8453"
maxBlockDist = 150
    [evm.networks.provider]
    type = "rpc"
    url = [
        "wss://base-rpc.publicnode.com",
        "wss://base.gateway.tenderly.co",
        "https://developer-access-mainnet.base.org",
        "https://base-public.nodies.app",
        "https://base-rpc.publicnode.com",
        "https://base.meowrpc.com",
        "https://mainnet.base.org",
        "https://base.lava.build"
    ]
