[[substrate.networks]]
name = "polkadot"
id = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc.ibp.network/polkadot",
    "wss://rpc.dotters.network/polkadot",
    "wss://polkadot-rpc.dwellir.com"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://polkadot-asset-hub-rpc.polkadot.io",
    "wss://asset-hub-polkadot-rpc.dwellir.com",
    "wss://statemint-rpc-tn.dwellir.com"
   ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2006"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc.astar.network",
    "wss://astar-rpc.dwellir.com"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2030"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://eu.bifrost-polkadot-rpc.liebi.com/ws",
    "wss://bifrost-polkadot-rpc.dwellir.com",
    "wss://hk.p.bifrost-rpc.liebi.com/ws"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2031"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://fullnode.centrifuge.io",
    "wss://centrifuge-rpc.dwellir.com",
    "wss://rpc-centrifuge.luckyfriday.io"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2032"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc-interlay.luckyfriday.io/",
    "wss://interlay-rpc.dwellir.com"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2034"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://hydradx.paras.ibp.network",
    "wss://hydradx.paras.dotters.network",
    "wss://rpc.helikon.io/hydradx"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2004"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://wss.api.moonbeam.network",
    "wss://moonbeam-rpc.dwellir.com"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2104"
relay = "urn:ocn:polkadot:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://ws.manta.systems"