[[substrate.networks]]
name = "polkadot"
id = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://rpc.ibp.network/polkadot",
    "wss://rpc.dotters.network/polkadot",
    "wss://polkadot-rpc.dwellir.com"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://polkadot-asset-hub-rpc.polkadot.io",
    "wss://asset-hub-polkadot-rpc.dwellir.com",
    "wss://statemint-rpc-tn.dwellir.com"
   ]

[[substrate.networks]]
id = "urn:ocn:polkadot:1002"
relay = "urn:ocn:polkadot:0"
    [substrate.networks.provider]
    type = "rpc"
    url = [
    "wss://sys.ibp.network/bridgehub-polkadot",
    "wss://bridge-hub-polkadot.dotters.network",
    "wss://bridge-hub-polkadot-rpc.dwellir.com",
    "wss://polkadot-bridge-hub-rpc.polkadot.io"
    ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2030"
relay = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://eu.bifrost-polkadot-rpc.liebi.com/ws",
    "wss://bifrost-polkadot-rpc.dwellir.com",
    "wss://hk.p.bifrost-rpc.liebi.com/ws"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2034"
relay = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://hydradx.paras.ibp.network",
    "wss://hydradx.paras.dotters.network",
    "wss://rpc.helikon.io/hydradx"
  ]

[[substrate.networks]]
id = "urn:ocn:polkadot:2004"
relay = "urn:ocn:polkadot:0"
  [substrate.networks.provider]
  type = "rpc"
  url = [
    "wss://wss.api.moonbeam.network",
    "wss://moonbeam-rpc.dwellir.com"
  ]

  ## Kusama

  [[substrate.networks]]
  id = "urn:ocn:kusama:0"
    [substrate.networks.provider]
    type = "rpc"
    url = [
      "wss://rpc.ibp.network/kusama",
      "wss://rpc.dotters.network/kusama",
      "wss://kusama.api.onfinality.io/public-ws"
    ]
  [[substrate.networks]]
  id = "urn:ocn:kusama:1000"
  relay = "urn:ocn:kusama:0"
    [substrate.networks.provider]
    type = "rpc"
    url = [
      "wss://sys.ibp.network/statemine",
      "wss://asset-hub-kusama.dotters.network",
      "wss://rpc-asset-hub-kusama.luckyfriday.io",
      "wss://kusama-asset-hub-rpc.polkadot.io",
      "wss://asset-hub-kusama-rpc.dwellir.com"
    ]
  [[substrate.networks]]
  id = "urn:ocn:kusama:1002"
  relay = "urn:ocn:kusama:0"
    [substrate.networks.provider]
    type = "rpc"
    url = [
      "wss://sys.ibp.network/bridgehub-kusama",
      "wss://bridge-hub-kusama.dotters.network",
      "wss://kusama-bridge-hub-rpc.polkadot.io"
    ]
