[[substrate.networks]]
id = "urn:ocn:rococo:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://rococo-rpc.polkadot.io"

[[substrate.networks]]
id = "urn:ocn:rococo:1000"
relay = "urn:ocn:rococo:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://rococo-asset-hub-rpc.polkadot.io"

[[substrate.networks]]
id = "urn:ocn:rococo:1013"
relay = "urn:ocn:rococo:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://rococo-bridge-hub-rpc.dwellir.com"

[[substrate.networks]]
id = "urn:ocn:westend:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://westend-rpc.polkadot.io"

[[substrate.networks]]
id = "urn:ocn:westend:1000"
relay = "urn:ocn:westend:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://westend-asset-hub-rpc.polkadot.io"

[[substrate.networks]]
id = "urn:ocn:westend:1002"
relay = "urn:ocn:westend:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://westend-bridge-hub-rpc.dwellir.com"