[[substrate.networks]]
id = "urn:ocn:alephzero:0"

  [substrate.networks.provider]
  type = "rpc"
  # wss://ws.azero.dev
  url = "wss://aleph-zero-rpc.dwellir.com"

[[substrate.networks]]
id = "urn:ocn:chainflip:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://mainnet-archive.chainflip.io"

[[substrate.networks]]
id = "urn:ocn:ternoa:0"

  [substrate.networks.provider]
  type = "rpc"
  url = "wss://mainnet.ternoa.network"