nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthIdent: null
    npmAlwaysAuth: false

npmPublishRegistry: "https://registry.npmjs.org"
