import { NetworkURN } from '@/services/types.js'

const setNetworks = <T extends Record<string, NetworkURN>>(network: T) => network

export const networks = setNetworks({
  polkadot: 'urn:ocn:polkadot:0',
  assetHub: 'urn:ocn:polkadot:1000',
  bridgeHub: 'urn:ocn:polkadot:1002',
  people: 'urn:ocn:polkadot:1004',
  coretime: 'urn:ocn:polkadot:1005',
  acala: 'urn:ocn:polkadot:2000',
  moonbeam: 'urn:ocn:polkadot:2004',
  composable: 'urn:ocn:polkadot:2019',
  astar: 'urn:ocn:polkadot:2006',
  nodle: 'urn:ocn:polkadot:2026',
  bifrost: 'urn:ocn:polkadot:2030',
  centrifuge: 'urn:ocn:polkadot:2031',
  interlay: 'urn:ocn:polkadot:2032',
  hydration: 'urn:ocn:polkadot:2034',
  phala: 'urn:ocn:polkadot:2035',
  manta: 'urn:ocn:polkadot:2104',
  pendulum: 'urn:ocn:polkadot:2094',
  polimec: 'urn:ocn:polkadot:3344',
  mythos: 'urn:ocn:polkadot:3369',
  hyperbridge: 'urn:ocn:polkadot:3367',
  kusama: 'urn:ocn:kusama:0',
  kusamaAssetHub: 'urn:ocn:kusama:1000',
  kusamaBridgeHub: 'urn:ocn:kusama:1002',
  kusamaCoretime: 'urn:ocn:kusama:1005',
  paseo: 'urn:ocn:paseo:0',
  paseoAssetHub: 'urn:ocn:paseo:1000',
  ethereum: 'urn:ocn:ethereum:1',
  arbitrum: 'urn:ocn:ethereum:42161',
  optimism: 'urn:ocn:ethereum:10',
  base: 'urn:ocn:ethereum:8453',
  bsc: 'urn:ocn:ethereum:56',
  gnosis: 'urn:ocn:ethereum:100',
  soneium: 'urn:ocn:ethereum:1868',
  polygon: 'urn:ocn:ethereum:137',
  unichain: 'urn:ocn:ethereum:130',
})
