{
 "title": "Ocelloids Service Node",
 "tags": [ "xcm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Websocket Listeners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (oc_socket_listener_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(oc_active_subscriptions_count[$__interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (__name__) (avg_over_time(oc_subscription_errors_count[$__interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oc_root_db_disk_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Notification Errors",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (origin, destination) (sum_over_time(oc_notifier_notification_error_total[$__interval]))",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (origin, destination) (sum_over_time(oc_notifier_notification_total[$__interval]))",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  { "title": "XCM Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total XCM Sent",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(oc_engine_out_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "XCM Execution Fail",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oc_engine_matched_total{outcome=\"Fail\"}",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  {
   "title": "XCM Asset Traps",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(origin) (oc_engine_trapped_total)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "XCM Delivered by Channel",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(oc_engine_matched_total)",
     "legendFormat": "{{origin}}-{{destination}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "oc_catcher_block_height", "legendFormat": "{{origin}}" }
   ]
  },
  {
   "title": "Finality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oc_catcher_block_finalized_seconds_sum[$__rate_interval])\n/ rate(oc_catcher_block_finalized_seconds_count[$__rate_interval])",
     "legendFormat": "{{origin}}"
    }
   ]
  }
 ]
}